### ISSUE TITLE
Rework archived repo feature

### ISSUE THREAD

**Issue by mmhxv3** [mmhxv3/4320Group18#4]
Right now, the feature tells how many days the repo is away from being archived. Maybe we should consider making it so the feature says whether the repo is active or not, and if inactive says how many days it has been inactive.

**Comment by sgoggins** [comment]
Define "archived" and "active". What does "inactive mean"? Is the repo inactive? They probably would not start tracking it. Though it could exist in a list and become archived. Maybe that's what you mean? We need a little more here.

**Comment by Whatever23333** [comment]
'Archived' is the status of last edited day of a project. It means the last day people pull the requests, commits, and the comments, or the pull requests are merged. 
Basically any operation above to the project will keep the project 'active'.
If any of these operation was done within a certain time period. The project is regarded as 'active'.
Otherwise, it is considered to be 'inactive'

**Comment by ElBureeto** [comment]
Changed the way archive repo works, where it is now works are on countdown timer system that tracks the last update to the repo, and then starts a countdown for 1 year after the last update.
